SELECT
	company,
	SUM(CASE value WHEN 'retention' THEN 1 ELSE 0 END) as retention,
	SUM(CASE value WHEN 'bonded-by-product' THEN 1 ELSE 0 END) as "bonded-by-product",
	SUM(CASE value WHEN 'new-tech' THEN 1 ELSE 0 END) as "new-tech",
	SUM(CASE value WHEN 'continuous-delivery' THEN 1 ELSE 0 END) as "continuous-delivery",
	SUM(CASE value WHEN 'internal-mobility' THEN 1 ELSE 0 END) as "internal-mobility",
	SUM(CASE value WHEN 'agile-dev' THEN 1 ELSE 0 END) as "agile-dev",
	SUM(CASE value WHEN 'engineering-driven' THEN 1 ELSE 0 END) as "engineering-driven",
	SUM(CASE value WHEN 'eq-iq' THEN 1 ELSE 0 END) as "eq-iq",
	SUM(CASE value WHEN 'project-ownership' THEN 1 ELSE 0 END) as "project-ownership",
	SUM(CASE value WHEN 'cross-dep' THEN 1 ELSE 0 END) as "cross-dep",
	SUM(CASE value WHEN 'flat-organization' THEN 1 ELSE 0 END) as "flat-organization",
	SUM(CASE value WHEN 'feedback' THEN 1 ELSE 0 END) as "feedback",
	SUM(CASE value WHEN 'fast-paced' THEN 1 ELSE 0 END) as "fast-paced",
	SUM(CASE value WHEN 'risk-taking' THEN 1 ELSE 0 END) as "risk-taking",
	SUM(CASE value WHEN 'rapid-growth' THEN 1 ELSE 0 END) as "rapid-growth",
	SUM(CASE value WHEN 'good-beer' THEN 1 ELSE 0 END) as "good-beer",
	SUM(CASE value WHEN 'parents' THEN 1 ELSE 0 END) as parents,
	SUM(CASE value WHEN 'open-source' THEN 1 ELSE 0 END) as "open-source",
	SUM(CASE value WHEN 'friends-outside-work' THEN 1 ELSE 0 END) as "friends-outside-work",
	SUM(CASE value WHEN 'product-driven' THEN 1 ELSE 0 END) as "product-driven",
	SUM(CASE value WHEN 'team-oriented' THEN 1 ELSE 0 END) as "team-oriented",
	SUM(CASE value WHEN 'internal-promotion' THEN 1 ELSE 0 END) as "internal-promotion",
	SUM(CASE value WHEN 'benefit-company' THEN 1 ELSE 0 END) as "benefit-company",
	SUM(CASE value WHEN 'physical-wellness' THEN 1 ELSE 0 END) as "physical-wellness",
	SUM(CASE value WHEN 'many-hats' THEN 1 ELSE 0 END) as "many-hats",
	SUM(CASE value WHEN 'open-communication' THEN 1 ELSE 0 END) as "open-communication",
	SUM(CASE value WHEN 'data-driven' THEN 1 ELSE 0 END) as "data-driven",
	SUM(CASE value WHEN 'diverse-team' THEN 1 ELSE 0 END) as "diverse-team",
	SUM(CASE value WHEN 'quality-code' THEN 1 ELSE 0 END) as "quality-code",
	SUM(CASE value WHEN 'lunch-together' THEN 1 ELSE 0 END) as "lunch-together",
	SUM(CASE value WHEN 'office-layout' THEN 1 ELSE 0 END) as "office-layout",
	SUM(CASE value WHEN 'flex-hours' THEN 1 ELSE 0 END) as "flex-hours",
	SUM(CASE value WHEN 'customer-first' THEN 1 ELSE 0 END) as "customer-first",
	SUM(CASE value WHEN 'pair-programs' THEN 1 ELSE 0 END) as "pair-programs",
	SUM(CASE value WHEN 'psychologically-safe' THEN 1 ELSE 0 END) as "psychologically-safe",
	SUM(CASE value WHEN 'engages-community' THEN 1 ELSE 0 END) as "engages-community",
	SUM(CASE value WHEN 'personal-growth' THEN 1 ELSE 0 END) as "personal-growth",
	SUM(CASE value WHEN 'creative-innovative' THEN 1 ELSE 0 END) as "creative-innovative",
	SUM(CASE value WHEN 'worklife-balance' THEN 1 ELSE 0 END) as "worklife-balance",
	SUM(CASE value WHEN 'inclusive' THEN 1 ELSE 0 END) as inclusive,
	SUM(CASE value WHEN 'junior-devs' THEN 1 ELSE 0 END) as "junior-devs",
	SUM(CASE value WHEN 'safe-env' THEN 1 ELSE 0 END) as "safe-env",
	SUM(CASE value WHEN 'remote-ok' THEN 1 ELSE 0 END) as "remote-ok",
	SUM(CASE value WHEN 'impressive-teammates' THEN 1 ELSE 0 END) as "impressive-teammates",
	SUM(CASE value WHEN 'light-meetings' THEN 1 ELSE 0 END) as "light-meetings",
	SUM(CASE value WHEN 'interns' THEN 1 ELSE 0 END) as interns
FROM hw3.keyvalues
GROUP BY company;

/* 67 rows, 47 columns */
